project:
  type: website
  output-dir: docs

website:
  title: "Ciclo de Gestión de los Datos. Ecoinformática"
  sidebar:
    background: primary
    # logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/ajpelu/teach_ecoinformatica_ugr
        text: GitHub
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: horario.qmd
        text: Horario
      - href: modulos.qmd
        text: Módulos

format:
  html:
    theme: yeti
    # css: styles.css
    toc: true

execute:
  freeze: auto

